/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVersionsRouteImport } from './routes/api/versions'
import { Route as ApiMusicRouteImport } from './routes/api/music'
import { Route as ApiDevStatsRouteImport } from './routes/api/dev-stats'
import { Route as ApiDevChatRouteImport } from './routes/api/dev-chat'
import { Route as ApiDevActionRouteImport } from './routes/api/dev-action'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthedChatRouteImport } from './routes/_authed/chat'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionsRoute = ApiVersionsRouteImport.update({
  id: '/api/versions',
  path: '/api/versions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMusicRoute = ApiMusicRouteImport.update({
  id: '/api/music',
  path: '/api/music',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevStatsRoute = ApiDevStatsRouteImport.update({
  id: '/api/dev-stats',
  path: '/api/dev-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevChatRoute = ApiDevChatRouteImport.update({
  id: '/api/dev-chat',
  path: '/api/dev-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevActionRoute = ApiDevActionRouteImport.update({
  id: '/api/dev-action',
  path: '/api/dev-action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedChatRoute = AuthedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthedChatRoute
  '/api/chat': typeof ApiChatRoute
  '/api/dev-action': typeof ApiDevActionRoute
  '/api/dev-chat': typeof ApiDevChatRoute
  '/api/dev-stats': typeof ApiDevStatsRoute
  '/api/music': typeof ApiMusicRoute
  '/api/versions': typeof ApiVersionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthedChatRoute
  '/api/chat': typeof ApiChatRoute
  '/api/dev-action': typeof ApiDevActionRoute
  '/api/dev-chat': typeof ApiDevChatRoute
  '/api/dev-stats': typeof ApiDevStatsRoute
  '/api/music': typeof ApiMusicRoute
  '/api/versions': typeof ApiVersionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authed/chat': typeof AuthedChatRoute
  '/api/chat': typeof ApiChatRoute
  '/api/dev-action': typeof ApiDevActionRoute
  '/api/dev-chat': typeof ApiDevChatRoute
  '/api/dev-stats': typeof ApiDevStatsRoute
  '/api/music': typeof ApiMusicRoute
  '/api/versions': typeof ApiVersionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/api/chat'
    | '/api/dev-action'
    | '/api/dev-chat'
    | '/api/dev-stats'
    | '/api/music'
    | '/api/versions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/api/chat'
    | '/api/dev-action'
    | '/api/dev-chat'
    | '/api/dev-stats'
    | '/api/music'
    | '/api/versions'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/auth'
    | '/_authed/chat'
    | '/api/chat'
    | '/api/dev-action'
    | '/api/dev-chat'
    | '/api/dev-stats'
    | '/api/music'
    | '/api/versions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDevActionRoute: typeof ApiDevActionRoute
  ApiDevChatRoute: typeof ApiDevChatRoute
  ApiDevStatsRoute: typeof ApiDevStatsRoute
  ApiMusicRoute: typeof ApiMusicRoute
  ApiVersionsRoute: typeof ApiVersionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/versions': {
      id: '/api/versions'
      path: '/api/versions'
      fullPath: '/api/versions'
      preLoaderRoute: typeof ApiVersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/music': {
      id: '/api/music'
      path: '/api/music'
      fullPath: '/api/music'
      preLoaderRoute: typeof ApiMusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev-stats': {
      id: '/api/dev-stats'
      path: '/api/dev-stats'
      fullPath: '/api/dev-stats'
      preLoaderRoute: typeof ApiDevStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev-chat': {
      id: '/api/dev-chat'
      path: '/api/dev-chat'
      fullPath: '/api/dev-chat'
      preLoaderRoute: typeof ApiDevChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev-action': {
      id: '/api/dev-action'
      path: '/api/dev-action'
      fullPath: '/api/dev-action'
      preLoaderRoute: typeof ApiDevActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/chat': {
      id: '/_authed/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthedChatRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedChatRoute: typeof AuthedChatRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedChatRoute: AuthedChatRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDevActionRoute: ApiDevActionRoute,
  ApiDevChatRoute: ApiDevChatRoute,
  ApiDevStatsRoute: ApiDevStatsRoute,
  ApiMusicRoute: ApiMusicRoute,
  ApiVersionsRoute: ApiVersionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
